# Generated by Django 4.2.9 on 2024-01-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Categoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-id', '-created'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zonalar'},
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(help_text='Aftorni tanlang', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aftor'),
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(help_text='Yangilikni tanasi', verbose_name='Tanasi'),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(to='main.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqti', verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(help_text='Yangilikni qisqacha tavsifi', max_length=600, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='new',
            name='hashtags',
            field=models.CharField(max_length=70, verbose_name='Xeshteg'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(help_text="Rasm qo'yish uchun joy", upload_to='news_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='new',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faoldir'),
        ),
        migrations.AlterField(
            model_name='new',
            name='shares',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Ulushlar'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Qarashlar'),
        ),
        migrations.AlterField(
            model_name='new',
            name='zone',
            field=models.ForeignKey(help_text='Zonani tanlang', on_delete=django.db.models.deletion.CASCADE, to='main.zone', verbose_name='Zona'),
        ),
    ]
