# Generated by Django 4.2.9 on 2024-02-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_new_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='views',
        ),
    ]
